
name: example
description: Example for flutter_offline_report package
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_offline_report:
    path: ../
  printing: ^5.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/templates/

